# Generated by Django 4.2.1 on 2023-06-04 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_skills_required'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='skills_required',
            new_name='skills',
        ),
    ]
