# Generated by Django 4.2.1 on 2023-06-04 02:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_event_location_event_address_event_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.TimeField(default=datetime.datetime(2023, 6, 4, 2, 28, 28, 419473, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2023, 6, 4, 2, 28, 28, 419454, tzinfo=datetime.timezone.utc)),
        ),
    ]
